#!/bin/bash
# Installer for ThePAK

# Source the banner script
source etc/banner

# Display the banner
echo -e "executing: ${LIGHTGREEN}SETUP${NOCOLOR}"
echo "-----------------------"

# Setup directory for Requirements
quickbms_dir="$PREFIX/share/quickbms"

# Function to display progress and start the main script
redirect() {
  echo -e "${LIGHTGREEN}STARTING THEPAK${NOCOLOR}"
  echo -ne '#####                     (33%)\r'
  sleep 1
  echo -ne '#############             (66%)\r'
  sleep 1
  echo -ne '#######################   (100%)\r'
  echo -ne '\n'
  bash thepak
}

# Function to check if quickbms is installed
quickbms_check() {
  echo -e "${YELLOW}Checking required program...${NOCOLOR}"
  if [[ -f "$quickbms_dir/quickbms" ]]; then
    echo -e "${LIGHTGREEN}Program has been installed.${NOCOLOR}"
    redirect
  else
    echo -e "${RED}PROGRAM NOT FOUND.${NOCOLOR}"
    quickbms_install
    redirect
  fi
}

# Function to install quickbms
quickbms_install() {
  echo -e "${LIGHTGREEN}Installing required program...${NOCOLOR}"
  wget -q http://aluigi.altervista.org/papers/quickbms_linux.zip
  unzip -qq quickbms_linux.zip
  mkdir -p "$quickbms_dir"
  chmod +x quickbms_4gb_files
  cp -rf quickbms_4gb_files "$quickbms_dir/quickbms"
  chmod +x etc/tools.bms thepak
  rm -rf quickbms*
  rm setup
  mkdir -p output
}

# Check and install required packages
echo -e "${YELLOW}Checking required packages...${NOCOLOR}"

packages=("wget" "unzip" "curl" "x11-repo" "qemu-system-i386" "qemu-user-i386")

for pkg in "${packages[@]}"; do
  if dpkg-query -W --showformat='${Status}\n' "$pkg" | grep -q "install ok installed"; then
    echo -e "${GREEN}${pkg}${NOCOLOR} is installed."
  else
    echo -e "${RED}No ${pkg}. Setting up ${pkg}.${NOCOLOR}"
    pkg install "$pkg" -y
  fi
done

# Check and install quickbms if needed
quickbms_check
